- hosts: all
  vars:
    my_packages: "{{ dict(packages.results|groupby('name')) }}"
  tasks:
    - dnf:
        list: updates
      register: packages

    - debug:
        msg: |
            {% for name, versions in my_packages.items() %}
            {% set max_ver=versions|map(attribute='version')|max %}
            {% set p=versions|selectattr('version', '==', max_ver)|list %}
            {{ name }}-{{ p.0.version }}-{{ p.0.release }}
            {% endfor %}
